### ISSUE TITLE
installation instructions?

### ISSUE THREAD

**Issue by dvera** [RepliconBioinfo/RepliconWrench#1]
Hello,

Do you have anything written up for how to install and use RepliconWrench?

Thanks,

Daniel

**Comment by ygindin** [comment]
Hi Daniel,

There is nothing to install, as RepliconWrench is a Java jar file and should work on any computer platform so long as it has Java installed.

To run RepliconWrench, you will need to have some familiarity with the command line.

To see the list of available tools packaged with RepliconWrench run:
`java -jar ~/Downloads/RepliconWrench.jar`
To see a help message associated with a specific tool, BedToIPLS in this case:
` java -jar ~/Downloads/RepliconWrench.jar BedToIPLS`
There are more details here: https://github.com/RepliconBioinfo/RepliconWrench/wiki/Replicon-Accessories

**Comment by qyodandan** [comment]
Hi Yevgeniy,
Is it possible to use Replicon to deal with bedgraph files?
Thanks,
Dandan

**Comment by ygindin** [comment]
Hey @qyodandan. If you mean, BedToIPLS - where you convert a BED time to a timing probabilities file, then yes. There shouldn't be a header in the file though.

**Comment by qyodandan** [comment]
I'm afraid not...
How to get the BED time file?
