### ISSUE TITLE
bedgraph file

### ISSUE THREAD

**Issue by qyodandan** [RepliconBioinfo/RepliconWrench#2]
Hi,
I think it's better to open a new discussion.
I  have bedgraph files from Dnase-I sequecing.
I searched online how to conver bedgraph file to bed file.
It showed that bedgraph files are bed files with additional UCSC track setting if I understood correctly.
But I can open bed files using editplus but failed to open bedgraph file.
I'm wondering whether these two files are different.
I a beginner of seq-data. It will be very nice if you can help me on this issue.
Thanks very much.
Dandan

**Comment by ygindin** [comment]
Bedgraph files are just space-delimited values files. You should be able to open them using any text editor. If you can't do that then you'll have to make sure that what you have is really a bedgraph file. The best place to get help would be https://www.biostars.org/.

**Comment by qyodandan** [comment]
Thank you very much. I can open bedgraph file now.
Sorry to take your time.
Dandan
